-- IF YOU UPDATE THIS FILE, DON'T FORGET TO INCREMENT THE Schema.VERSION!
-- This is a table for element references. Table name
-- is substituted in a runtime.

CREATE TABLE IF NOT EXISTS {0}(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	OFFSET INT NOT NULL,
	LENGTH INT NOT NULL,
	NAME VARCHAR_IGNORECASE NOT NULL,
	METADATA VARCHAR,
	QUALIFIER VARCHAR,
	FILE_ID INT NOT NULL,
	FOREIGN KEY(FILE_ID) REFERENCES FILES(ID) ON UPDATE CASCADE ON DELETE CASCADE,
);