-- IF YOU UPDATE THIS FILE, DON'T FORGET TO INCREMENT THE Schema.VERSION!
-- This is a table for element declarations. Table name
-- is substituted in a runtime.

CREATE MEMORY TABLE IF NOT EXISTS {0}(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	FLAGS INT NOT NULL,
	OFFSET INT NOT NULL,
	LENGTH INT NOT NULL,
	NAME_OFFSET INT NOT NULL,
	NAME_LENGTH INT NOT NULL,
	NAME VARCHAR_IGNORECASE NOT NULL,
	CC_NAME VARCHAR_IGNORECASE, 
	METADATA VARCHAR, 
	QUALIFIER VARCHAR, 
	PARENT VARCHAR, 
	FILE_ID INT NOT NULL, 
	FOREIGN KEY(FILE_ID) REFERENCES FILES(ID) ON UPDATE CASCADE ON DELETE CASCADE, 
);